// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCoHRd3aEleMolij3-QBCWvk3gwag_bq00',
    appId: '1:375487918338:web:0d7a2893513875a653121b',
    messagingSenderId: '375487918338',
    projectId: 'washingout-61b50',
    authDomain: 'washingout-61b50.firebaseapp.com',
    storageBucket: 'washingout-61b50.appspot.com',
    measurementId: 'G-T0SGN823DE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAwDzzz4QJaGXKdKK5wY75WoLzRrA5wCnI',
    appId: '1:375487918338:android:a99b6c0ef5ee7c0653121b',
    messagingSenderId: '375487918338',
    projectId: 'washingout-61b50',
    storageBucket: 'washingout-61b50.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDjpa7Oum6Z43ecy7lk5X5yKcqnZdUCxYM',
    appId: '1:375487918338:ios:cf3b870ce96d997853121b',
    messagingSenderId: '375487918338',
    projectId: 'washingout-61b50',
    storageBucket: 'washingout-61b50.appspot.com',
    iosBundleId: 'com.example.washOut',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDjpa7Oum6Z43ecy7lk5X5yKcqnZdUCxYM',
    appId: '1:375487918338:ios:cf3b870ce96d997853121b',
    messagingSenderId: '375487918338',
    projectId: 'washingout-61b50',
    storageBucket: 'washingout-61b50.appspot.com',
    iosBundleId: 'com.example.washOut',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCoHRd3aEleMolij3-QBCWvk3gwag_bq00',
    appId: '1:375487918338:web:3e0c913c2df0463b53121b',
    messagingSenderId: '375487918338',
    projectId: 'washingout-61b50',
    authDomain: 'washingout-61b50.firebaseapp.com',
    storageBucket: 'washingout-61b50.appspot.com',
    measurementId: 'G-8JE77WTP61',
  );
}
